# -*- coding: utf-8 -*-
"""Deliverable 6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nDP4kNIY8Oszmh48mrGvPCLD3x3nH6Qe
"""

import pandas as pd
import numpy as np
import seaborn as sns

iris = sns.load_dataset('iris')
iris.head()

iris.drop(labels = 'species', axis = 1, inplace = True)
iris.head()

iris['sepal_sum'] = iris['sepal_length'] + iris['sepal_width']
iris['petal_sum'] = iris['petal_length'] + iris['petal_width']
iris.head()

header = ['sepal_length', 'sepal_width', 'sepal_sum', 'petal_length', 'petal_width', 'petal_sum']

mean = [np.mean(iris['sepal_length']),
        np.mean(iris['sepal_width']),
        np.mean(iris['sepal_sum']),
        np.mean(iris['petal_length']),
        np.mean(iris['petal_width']),
        np.mean(iris['petal_sum'])]

std = [np.std(iris['sepal_length']),
        np.std(iris['sepal_width']),
        np.std(iris['sepal_sum']),
        np.std(iris['petal_length']),
        np.std(iris['petal_width']),
        np.std(iris['petal_sum'])]

min = [np.min(iris['sepal_length']),
        np.min(iris['sepal_width']),
        np.min(iris['sepal_sum']),
        np.min(iris['petal_length']),
        np.min(iris['petal_width']),
        np.min(iris['petal_sum'])]

max = [np.max(iris['sepal_length']),
        np.max(iris['sepal_width']),
        np.max(iris['sepal_sum']),
        np.max(iris['petal_length']),
        np.max(iris['petal_width']),
        np.max(iris['petal_sum'])]

mean = list(iris.mean())

summary_dict = {'mean' :mean,
                'std' :std,
                'min' :min,
                'max' :max}

summary_df = pd.DataFrame(data = summary_dict)
summary_df.index = ['sepal_length', 'sepal_width', 'sepal_sum', 'petal_length', 'petal_width', 'petal_sum']

summary_df